alias   cx="rack-gateway"
alias  cxx="convox"

alias  cxs="rack-gateway switch staging"
alias  cxp="rack-gateway switch us"
alias cxeu="rack-gateway switch eu"
# alias cxs="convox switch staging"
# alias cxp="convox switch us"
# alias cxeu="convox switch eu"

alias  cxr="rack-gateway rack"
alias  cxe="rack-gateway exec"
alias cxru="rack-gateway run"
alias  cxd="rack-gateway deploy --wait"
alias  cxl="rack-gateway logs"
alias cxrs="rack-gateway resources"
alias cxsc="rack-gateway scale"
alias  cxi="rack-gateway instances"
alias cxrl="rack-gateway releases"
alias  cxb="rack-gateway builds"
alias cxps="rack-gateway ps"
