alias   cx="convox-gateway convox"
alias  cxg="convox-gateway"
alias  cxx="convox"

alias  cxs="convox-gateway switch staging"
alias  cxp="convox-gateway switch us"
alias cxeu="convox-gateway switch eu"
# alias cxs="convox switch staging"
# alias cxp="convox switch us"
# alias cxeu="convox switch eu"

alias  cxr="convox-gateway convox rack"
alias  cxe="convox-gateway convox exec"
alias cxru="convox-gateway convox run"
alias  cxd="convox-gateway convox deploy --wait"
alias  cxl="convox-gateway convox logs"
alias cxrs="convox-gateway convox resources"
alias cxsc="convox-gateway convox scale"
alias  cxi="convox-gateway convox instances"
alias cxrl="convox-gateway convox releases"
alias  cxb="convox-gateway convox builds"
alias cxps="convox-gateway convox ps"
