alias rn='react-native'
alias rnl='react-native link'
# The React Native packager often crashes.
alias rns='while true; do react-native start; done'
alias rnsr='react-native start --reset-cache'
alias rni='react-native run-ios'
alias rnir='react-native run-ios --configuration "Release"'
alias rnid='react-native run-ios --device'
alias rnird='react-native run-ios --configuration "Release" --device'
alias rnli='react-native log-ios'
alias rna='react-native run-android'
alias rnar='react-native run-android --variant=release'
alias rnas='react-native run-android --variant=releaseStaging'
alias rnla='react-native log-android'
alias rnw='react-native run-windows'
alias rnwp='react-native run-wpf'
